### ISSUE TITLE
Investigate how no squale parameters affect a Check in Sonar

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#101]
1) Whole test was ignored `test()`, it need to removed or make it work. IntelijIdea inspection is complaining about this Ignore annotation.

2) We have list of Checks that are not having sqale parameters
https://github.com/checkstyle/sonar-checkstyle/blob/master/checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java#L34
Not clear why such Checks are so special.

most issues were added as fix for build failure - https://github.com/checkstyle/sonar-checkstyle/blame/6b53207becaf77253a92a684e06c58b80317457f/checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/CheckstyleRulesDefinitionTest.java

**Comment by romani** [comment]
`debtSubCharacteristic()` is deprecated and always return null in api 5.6.6, so I removed its usage from UT.

https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L1014

**Comment by romani** [comment]
point "1)" is fixed.

If smb have time to investigate/fix "2)" - please be welcome.

**Comment by muhlba91** [comment]
related to #219 - closing this.
