### ISSUE TITLE
Default value of ParameterName accessModifiers is wrong

### ISSUE THREAD

**Issue by marschall** [checkstyle/sonar-checkstyle#103]
Sonar version: 5.6.5
Checkstyle sonar plugin verson: 3.6.1

Steps to reproduce or description of problem:

Create an SonarQube quality profile by importing the following Checkstyle configuration

```xml
<module name="Checker">
    <module name="TreeWalker">
        <module name="ParameterName"/>
    </module>
</module>
```

The import will fail because the default value of the `accessModifiers` property is `public, protected, package, private` (a space after each comma) but it should be `public,protected,package,private` (no space after each comma)

**Comment by romani** [comment]
fix is merged.
There are more cases like this in code, I will try to make issue on it.
It would be good to make UT on this as config is too big to keep it in sync manually

**Comment by marschall** [comment]
What is UT? Yes, ideally the `rules.xml` would be generated.

**Comment by romani** [comment]
UT - unit test, we already UT for it, but it not ideal.

> ideally the rules.xml would be generated.

no arguing, but no people who can do this. Validation will be good even for generated file.
So we support it step by step.
