### ISSUE TITLE
Default value for ParameterNumber max is missing

### ISSUE THREAD

**Issue by marschall** [checkstyle/sonar-checkstyle#105]
Sonar version: 5.6.5
Checkstyle sonar plugin verson: 3.6.1

Steps to reproduce or description of problem:

Create an SonarQube quality profile by importing the following Checkstyle configuration

```xml
<module name="Checker">
    <module name="TreeWalker">
        <module name="ParameterNumber"/>
    </module>
</module>
```

The import fails because no value for the `max` property is supplied. This should work because `max` property has a default value of 7

http://checkstyle.sourceforge.net/config_sizes.html#ParameterNumber

**Comment by romani** [comment]
fix is merged

**Comment by marschall** [comment]
@romani no only if ones with default values should have the same default value in the `rules.xml`
