### ISSUE TITLE
Wrong javadocTokens values for NonEmptyAtclauseDescriptionCheck

### ISSUE THREAD

**Issue by dancing-leaves** [checkstyle/sonar-checkstyle#114]
Sonar version: 6.3.1
Checkstyle sonar plugin verson: 3.7

Steps to reproduce or description of problem:
Activate "Non Empty At-clause Description", specify valid javadocTokens tokens.
http://checkstyle.sourceforge.net/config_javadoc.html#NonEmptyAtclauseDescription

![tokens](https://cloud.githubusercontent.com/assets/6843260/26834897/58285fe4-4adf-11e7-8f08-4192adc89712.png)

**Comment by romani** [comment]
will be released somewhere this month, we are waiting for 7.8.2 from checkstyle library.
You can build plugin yourself.
