### ISSUE TITLE
Error creating custom rule for Javadoc rules

### ISSUE THREAD

**Issue by jlarfors** [checkstyle/sonar-checkstyle#119]
Sonar version: Version 6.4 (build 25310) 
Checkstyle sonar plugin verson: 3.7

Steps to reproduce or description of problem:
1. Go to SonarQube rules
2. Select, for example, Javadoc Method template
3. Click to Create a Custom Rule
4. Enter minimal data, e.g. "Test" for name, key, description
5. Press Create and you get the following error:
_Value '' must be one of : nothing, public, protected, package, private, anoninner._
![image](https://user-images.githubusercontent.com/1135394/28922282-233fbb1e-7862-11e7-90e0-67cd3d705fc0.png)

I reproduced this for Javadoc Method and Javadoc Type, but might occur for the others as well

**Comment by jlarfors** [comment]
Hello, I found that adding "nothing" into the excludeScope field makes this work.
Would be nice if this was a bit clearer/default behaviour

**Comment by romani** [comment]
Looks like some problem in metadata config for this Check

**Comment by rnveach** [comment]
The empty double quotes is similar to https://github.com/checkstyle/sonar-checkstyle/issues/88

**Comment by muhlba91** [comment]
we moved to a new metadata mechanism, and properties (types, ...) are set based on this. closing this as stale, and should be fixed. please reopen if issue still persists with new up-to-date information.
