### ISSUE TITLE
When checkstyle3.7 installed, there is "no profiles found"

### ISSUE THREAD

**Issue by svw-cid-63303** [checkstyle/sonar-checkstyle#120]
Sonar version: [[5.6.6]]
Checkstyle sonar plugin verson: [[3.7]]
JDK: 1.8.0_45
OS: Windows 2008 R2
DB: MySQL 5.7

Steps to reproduce or description of problem:

When checkstyle3.7 installed, it shows in "update center", like the screenshot below.
<img width="945" alt="17 08 16 1415_2" src="https://user-images.githubusercontent.com/31059019/29349608-6f7d6e88-828d-11e7-9dd4-a8c24db4d39f.png">
But there is "No profiles found", now the checkstyle jar doesn't work.
<img width="775" alt="17 08 16 1403_1" src="https://user-images.githubusercontent.com/31059019/29349551-39473970-828d-11e7-9a76-5d091dff6bc8.png">
How can I solve this problem? Please give me some suggestion, thanks.

**Comment by romani** [comment]
@svw-cid-63303 , checkstyle sonar plugin does not import any profiles to Sonar server. 
To verify that plugin is installed, please search for rules like at https://raw.githubusercontent.com/checkstyle/resources/master/img/sonar-wiki/sonar-in-docker.PNG

**Comment by romani** [comment]
Please use import of checktyle config file to create profile - https://github.com/checkstyle/sonar-checkstyle/wiki/How-to-import-existing-checkstyle-config-to-sonar

**Comment by svw-cid-63303** [comment]
@romani Thanks for giving suggestion. I have got the way to import the config file manually. But I still have a question, where can I find the "Checkstyle config file" to import?  Is it in the "checkstyle-sonar-plugin-3.7.jar"? Please give me some download URL or file names address. Thanks a lot.

**Comment by romani** [comment]
Sonar plugin 3.7 depends on checkstyle 7.7 - https://github.com/checkstyle/sonar-checkstyle/blob/master/README.md
All config files are checkstyle repository https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-7.7 , 

Files are at: https://github.com/checkstyle/checkstyle/tree/checkstyle-7.7/src/main/resources
