### ISSUE TITLE
Rule Javadoc Method cannot be activated

### ISSUE THREAD

**Issue by naerion89** [checkstyle/sonar-checkstyle#122]
Sonar version: 6.5
Checkstyle sonar plugin verson: 3.7

Steps to reproduce or description of problem:

Why rule Javadoc Method cannot be activated in sonar profile ?
Only rule javadoc package can be activate.

Regards,

**Comment by romani** [comment]
@naerion89 ,

please share a screenshot of what you see in your sonarqube .

**Comment by naerion89** [comment]
here is the new profile : 

![quality_profiles](https://user-images.githubusercontent.com/30294729/29603701-706763f0-87e5-11e7-9a65-2b0288b83273.png)

with the tag comments, i can only activate rule javadoc package : 
![quality_rules](https://user-images.githubusercontent.com/30294729/29603700-70669c22-87e5-11e7-9021-8b6507c7a366.png)

**Comment by romani** [comment]
Please click on required checkstyle Check (second screenshot) provide all required parameters for Check, sonar will force you to make a named rule on your configurations. Such a rule could be activated in profile.

Checks are highly configurable, so you can make few instances of the same Check, such instances are named a Rule in sonar.

Only checks without configuration could be activated right away in Sonar.

https://stackoverflow.com/a/26977345/1015848
