### ISSUE TITLE
any way to import results of eslint, tslint or stylelint?

### ISSUE THREAD

**Issue by gucong3000** [checkstyle/sonar-checkstyle#125]
I am using [eslint](https://eslint.org/) to check my js, and [eslint can output results to `checkstyle-result.xml`](https://eslint.org/docs/user-guide/formatters/#checkstyle).
Is there any way just import this file to sonar? It is [a nodejs project without anything about java](https://github.com/gucong3000/gulp-reporter).

**Comment by romani** [comment]
there is no way to do this by checkstyle-sonar plugin.

Other plugins used the same output format only because bunch existing ways to show checkstyle results in some services - jenkins, ...... .

But formats could become different at any time

**Comment by gucong3000** [comment]
That project is a gulp plugin for convert the results of lints for front-end languages. Is there any thing i can do for this issue?

**Comment by romani** [comment]
no.
nothing with be done in this project to help other projects. Sorry.
