### ISSUE TITLE
Regarding the remediation cost of checkstyle rule

### ISSUE THREAD

**Issue by sharieffmd** [checkstyle/sonar-checkstyle#126]
Sonar version: [5.6.6]
Checkstyle sonar plugin version: [3.6.1]

Subject:

I have a doubt regarding changes in remediation cost of check-style rule from linear:1d to Constant/issue:1h.

I'm not sure, from which version of SonarQube the remediation cost has changed for Check-style rule.

However, we are using open source version of SonarQube from long time and upgraded SonarQube versions from 3.7.4 to 5.0.1,5.1.2,5.6.0 and now 5.6.6 and the check-style remediation cost is linear:1d.

Now , we have hosted a new instance of SonarQube version - 5.6.6 (fresh database) and we observed that the remediation cost of check-style rule is Constant/issue:1h.

So, Just for checking the remediation cost on the older versions with fresh database. I've installed 5.0.1,5.1.2,5.6.0(All fresh installation). I observed that the remediation cost of check-style rule is Constant/issue:1h.

So, could you please let me know from which version of SonarQube the remediation cost has changed and is there a way to fix this on the existing SonarQube instance where the remediation cost is linear:1d. Any suggestions will be helpful.

Thanks & Regards,
Sharieff.

**Comment by romani** [comment]
@sharieffmd , 
all that metadata is located at https://github.com/checkstyle/sonar-checkstyle/blob/master/checkstyle-sonar-plugin/src/main/resources/com/sonar/sqale/checkstyle-model.xml
you can review "blame" mode and see when all values changed. 
In my memory it was not changed for last year for sure.

**Comment by sharieffmd** [comment]
Thanks a lot for the above link.

I'll check it.

**Comment by romani** [comment]
if there is some certain items to improve - please open new certain issue.
