### ISSUE TITLE
HideUtilityClassConstructorCheck should be marked as deprecated (works the same as squid:S1118)

### ISSUE THREAD

**Issue by agabrys** [checkstyle/sonar-checkstyle#138]
Sonar version: 5.6.7
Checkstyle sonar plugin verson: 3.7

Steps to reproduce or description of problem:

Hello. There is a convention that all rules which do the same things as rules provided by SQUID should be marked as deprecated. Today I found that the rule `checkstyle:com.puppycrawl.tools.checkstyle.checks.design.HideUtilityClassConstructorCheck` works the same as `squid:S1118`([Utility classes should not have public constructors](https://sonarcloud.io/organizations/default/rules#rule_key=squid%3AS1118)).

Best Regards

**Comment by romani** [comment]
>There is a convention that all rules which do the same things as rules provided by SQUID should be marked as deprecated.

:).
please disable squid rule, checkstyle works NOT only in Sonar, not only for Sonar.
Occasional overlap in behavior is possible, but it does not mean that it is same in quality and ....

**Comment by agabrys** [comment]
> checkstyle works NOT only in Sonar, not only for Sonar

I didn't want to disable the rule in the Checkstyle analyzer, but only in Sonar Checkstyle plugin 😉 PMD plugin has a lot of rules marked as deprecated only in SonarQube environment.

> please disable squid rule

I understand your point of view. I just noticed that all `Deprecated` rules with a comment "use squid..." are in `Ready` status right now, so my information has been a little bit outdated :confused:

Ps. We always prefer to use squid rules because only they are checked by SonarLint.

**Comment by romani** [comment]
http://dist.sonarsource.com/reports/coverage/checkstyle.html here is Sonar's "deprecation" page
it is inaccurate in most cases, it is not deprecation - it is full overlap, partial overlap.
That is why firs what I did in plugin is removed all deprecation labels. They cannot deprecate smth that does not belong to them and never did.

I am ok to be transparent to user to let them decide what to use. But mapping table  should look at Rule/check/Inspection design and possibilities. Checks are more flexible then Squid rules.

If you are interested you can create web page is "overlap" mapping and i will be happy to host it in offical project page.

> Ps. We always prefer to use squid rules because only they are checked by SonarLint.

you are right in decision to do what is best works to you and your team. I always encourage users use all tools and choose what they like more in each of them to have maximal quality gate. In overlap it is even better to have complains from all tools on the same problem, as extra prove that it is not good code at all.
