### ISSUE TITLE
SonarQube marketplace shows Checkstyle 3.7 as the latest version

### ISSUE THREAD

**Issue by agabrys** [checkstyle/sonar-checkstyle#139]
Hi,
Today I realized that the latest released version of the Checkstyle SonarQube plugin is 4.5. Unfortunately SonarQube Marketplace (6.7) and Update Center (5.6.7) show that the latest version is 3.7.

![marketplace](https://user-images.githubusercontent.com/10604335/34643751-f43ce88a-f329-11e7-908c-3227e5ae99b8.png)

Environment:
* SonarQube: 6.7 and 5.6.7

Best Regards

**Comment by romani** [comment]
yes, sorry for delay, I will  put 4.7  to Sonar plugin center in few days.

**Comment by romani** [comment]
4.7 is on the way - https://groups.google.com/forum/#!topic/sonarqube/8HCMy6qLQ0M
in two weeks will appear in Sonar  plugin center.
