### ISSUE TITLE
Many false positive issues after upgrading from SonarQube 4.5 to 5.6 LTS

### ISSUE THREAD

**Issue by softdays** [checkstyle/sonar-checkstyle#14]
I'm facing a big issue after upgrading from SonarQube 4.5.4 to LTS 5.6: the new analyzes rise hundreds of new issues (which are false positives). These news issues are primarily related to the following CheckStyle rules : NoLineWrapCheck and WhitespaceAroundCheck. This is very strange because I was using the same 2.4 version of the sonar checkstyle plugin with the previous version.

It seems that the rule engine does't recognize the language anymore. See for example the alerts on diamond operators or annotation on class declaration in the attached screenshots.

First clue: the incriminated rules seems to be "template rules" and SQ displays this warning in the rule's details: "'This rule template was activated on the following profiles in previous versions of SonarQube. It is not possible anymore to do so. Instead, please create a custom rule." But I already got this same message when I was using the version 4.5.4!

I have tried to replace an old "template rule" by a custom rule but same results.

Do anyone have any idea what is going wrong?

![2016-07-08 13_30_33-sonarqube - src_main_java_fr_edu_scolarite_lsun_bilan_batch_etablissement](https://cloud.githubusercontent.com/assets/948293/16691006/fa3162a6-452a-11e6-938f-651b2e3ddae1.png)
![2016-07-08 13_31_39-sonarqube - src_main_java_fr_edu_scolarite_lsun_bilan_batch_division](https://cloud.githubusercontent.com/assets/948293/16691008/fc09ef30-452a-11e6-9cf3-2cc8efebee7d.png)

**Comment by romani** [comment]
Please provide more details on this problem:
What is your config for checkstyle for this Checks ? Can you do export or share screenshots.

Please also try our 3.1 version, there were number of fixes for mismatch of Checks and metadata for sonar integration.

**Comment by romani** [comment]
@softdays , please test our recent versions .
if no feedback in 2 weeks, I will close this issue.

**Comment by romani** [comment]
no details are provided, issue is closed.
