### ISSUE TITLE
Upgrading to CheckStyle plugin 4.8 with SonarQube 6.2 causes analysis to fail in Jenkins

### ISSUE THREAD

**Issue by kmandeville** [checkstyle/sonar-checkstyle#144]
Sonar version: 6.2
Checkstyle sonar plugin verson: 4.8

I recently upgraded the CheckStyle plugin to 4.8. After doing so, SonarQube interface seemed to still work fine. But the next build that ran that tried to run the SonarQube analysis failed when it tried to run CheckStyle. There was no information in the build and nothing that I could find in the sonar logs

**Comment by rnveach** [comment]
> upgraded the CheckStyle plugin to 4.8

What was the version you were using before?
Did you check on the rules related to any of the breaking changes specified in the Checkstyle utility between the 2 versions?
http://checkstyle.sourceforge.net/releasenotes.html

**Comment by romani** [comment]
> SonarQube analysis failed when it tried to run CheckStyle.

please read logs of sonar to get a reason. Please pay attention to braking changes between releases to resolve  issues.

**Comment by kmandeville** [comment]
I don't see anything in sonar.log when it fails. And the breaking changes
don't highlight specific rules that might no longer work. I uninstalled the
plugin and reinstalled and still get the failure. I deactivated every rule
and the failures stop. I will have to go through one by one to figure out
which rule or rules are causing the problem. But why would that rule still
exist if it is broken now? Thats what i don't understand.

**Comment by rnveach** [comment]
> But why would that rule still exist if it is broken now? Thats what i don't understand.

We have no way, right now, to get list of rules you define and see if they are still correct or not. This is an issue with either us not knowing Sonar's API system or with Sonar not giving us access to this information. We don't know the API well enough to know if this type of check is possible or how we would do it.

> And the breaking changes don't highlight specific rules that might no longer work. 

If you would tell us the 2 versions, we could help you narrow down which rule is at fault.

**Comment by kmandeville** [comment]
Where do the CheckStyle rules come from that show up in Sonar? Did I
possibly have an old rule already assigned to my Quality Profile that was
still there even after uninstalling the plugin and reinstalling? Are the
CheckStyle rules part of the plugin? So wouldn't updating the plugin or
uninstalling/reinstalling remove any rules that broke? Sorry if I'm not
understanding how they work.

Screenshot of the Jenkins build error you want to see? Doesn't say much:

**Comment by romani** [comment]
> Where do the CheckStyle rules come from that show up in Sonar?

all rules are in plugin, configuration is in Sonar DB.

> Did I possibly have an old rule already assigned to my Quality Profile that was still there even after uninstalling the plugin and reinstalling?

you provide no details ... I do not now.

> Are the CheckStyle rules part of the plugin?

yes, but rules configurations are stored in Sonar DB.

> So wouldn't updating the plugin or uninstalling/reinstalling remove any rules that broke?

I think Sonar just disable them.

============================

so remove all checkstyle rules from Sonar and create them from scratch if that is so weird on your side.

**Comment by morsmodre** [comment]
I'm having a very similar problem. After migrating to the plugin versions 4.8 I have the following error:

> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project common-libs: Can not execute Checkstyle: SuppressionCommentFilter is not allowed as a child in Checker -> [Help 1]

In sonar (version 6.7.2), I have some 3000 rules. So my questions are:
 * Could I see which of these rules and checkstyle rules?
 * Is there a way to see the checkstyle-config used in sonar (not sure if sonar uses one)?
 * In sonar what is the SuppressionCommentFilter rule?

Thanks!

**Comment by rnveach** [comment]
> Is there a way to see the checkstyle-config used in sonar (not sure if sonar uses one)?

Yes, it generates a checkstyle xml config file and then behind the scenes passes that to checkstyle utility. I don't remember where that file is placed.
https://github.com/checkstyle/sonar-checkstyle/blob/d20b6a3c19ea1f7c7432544b68134c38dabde2e9/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstyleConfiguration.java#L68

> In sonar what is the SuppressionCommentFilter rule?

Try looking for something named `Treewalker Filters` and `Checker Filters`.
https://github.com/checkstyle/sonar-checkstyle/blob/7841a5292bce9e1b5938e9d94ec2dc801d913c49/checkstyle-sonar-plugin/src/main/java/org/sonar/plugins/checkstyle/CheckstylePlugin.java#L73

**Comment by romani** [comment]
> Could I see which of these rules and checkstyle rules?

just search for them
![image](https://user-images.githubusercontent.com/812984/39951383-2c35b5e8-553e-11e8-9c7e-893c8096ee09.png)
one any rule details and it will should from where it comes.

@morsmodre , did you resolve you problem ?

@kmandeville, did you resolve your problem ?

**Comment by romani** [comment]
no response for long time, minimal supported version is 6.7 now.
