### ISSUE TITLE
Support multiple Separator Wrap rule instances

### ISSUE THREAD

**Issue by jgchristian** [checkstyle/sonar-checkstyle#145]
Sonar version: 6.7.1
Checkstyle sonar plugin verson: 4.8

Steps to reproduce or description of problem:
- Attempt to activate multiple instances of the "Separator Wrap" rule to line up with Google Style Guide: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L84
- Presently this rule is not configured in the plugin as having multiple cardinality (i.e. a Sonar rule template) so only one instance can be activated.

====================
Migration notes:
On existing rules there will be warning " This rule template was activated on the following profiles in previous versions of SonarQube. It is not possible anymore to do so. Instead, please create a custom rule. "
It will continue to work as before, to resolve warning just recreate Rule in SoanrQube.

**Comment by rnveach** [comment]
This check is probably not the only one who needs to be fixed.
Eventually the UT should validate the check's carnality defined by the rules setup in https://github.com/checkstyle/sonar-checkstyle/issues/87 .

**Comment by rnveach** [comment]
Fix was merged
