### ISSUE TITLE
Provide proper cardinality for Checks

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#147]
Base on issue #145 .

Most of our Check supposed to have multiple of instances in configuration.
But now it is not possible some of them do not have `<cardinality>MULTIPLE</cardinality>`

It is required to review all Checks and add `<cardinality>MULTIPLE</cardinality>` to all which can have multiple instances.
Usually if Check have at least one property that user can configure it mean that Check could have multiple instances, with different configuration. But there are some single property Chevks that could conflict with each other if two instances exists , so such Checks should stay as is now.

Such update is not for bugfix release of plugin, it should be done for minor checkstyle version bump.

**Comment by rnveach** [comment]
This isn't must different then https://github.com/checkstyle/sonar-checkstyle/issues/87 and that issue contains the rules for assigning cardinality.

**Comment by muhlba91** [comment]
this is fixed as per new metadata mechanism. closing this.
