### ISSUE TITLE
Readme incorrect: 8.10.1 -> 8.11 for latest

### ISSUE THREAD

**Issue by hosszubalazs** [checkstyle/sonar-checkstyle#153]
Dear CheckStyle Team!

The table at the beginning of the README states 4.11 plugin uses Checkstyle 8.10.1 . Based on the changes and the release notes this is incorrect.
Sonar Checkstyle 4.11 uses CheckStyle 8.11, not 8.10.1. Please update the README.

Thanks and cheers,
Balázs

**Comment by rnveach** [comment]
https://github.com/checkstyle/sonar-checkstyle/commit/7e3651ccef41050627c80a1437e986ad5e98b2bf#diff-04c6e90faac2675aa89e2176d2eec7d8
It looks like the row was just duplicated and not updated. The pom specifies 8.11 .

**Comment by romani** [comment]
Fix is merged
