### ISSUE TITLE
Allow add default checkstyle config with more long text

### ISSUE THREAD

**Issue by truyet** [checkstyle/sonar-checkstyle#155]
Sonar version: 7.2.1
Checkstyle sonar plugin verson: 4.11

Steps to reproduce or description of problem:
Go to Administration -> Configuration -> General Settings -> Java -> Checkstyle
Copy TreeWalker module content in [google check](https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml)

Save with error:
<img width="970" alt="screen shot 2018-08-10 at 2 09 06 pm" src="https://user-images.githubusercontent.com/710057/43943977-9c086d42-9ca7-11e8-9b52-1a2afef66666.png">

**Comment by romani** [comment]
Please do not put Checks to field for filters.
For general Checks in your existing config you need to import them to sonar, if import does not work, do manual recreation all Checks in sonar ui
