### ISSUE TITLE
Fix TeamCity

### ISSUE THREAD

**Issue by rnveach** [checkstyle/sonar-checkstyle#160]
https://teamcity.jetbrains.com/viewLog.html?buildId=1639807&tab=Inspection&buildTypeId=Checkstyle_SonarCheckstyleIdeaInspectionsPullRequest

 Declaration redundancy
Redundant throws clause (Errors) (1)
 Java 8
Statement lambda can be replaced with expression lambda (Errors) (1)
 Performance
'Collection.toArray()' call style (Errors) (1)

`toArray` causes issues with PMD, but main repo doesn't have this problem.

**Comment by rnveach** [comment]
Fix was merged

**Comment by romani** [comment]
TC is green on master
