### ISSUE TITLE
update all dtd files to reference to most latest versions at checkstyle.org

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#188]
update all dtd files to reference to most latest versions at checkstyle.org

all dtds - https://github.com/checkstyle/checkstyle.github.io/tree/master/dtds

import_control_1_3.dtd --> 1_4
suppressions_1_1.dtd --> suppressions_1_2_xpath_experimental.dtd
configuration_1_2.dtd --> configuration_1_3.dtd

**Comment by rnveach** [comment]
Fix was merged
