### ISSUE TITLE
SonarQube 7.6 deprecated org.sonar.api.batch.ScannerSide

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/sonar-checkstyle#194]
In SQ 7.6 `org.sonar.api.batch.ScannerSide` got deprecated and replaced by `org.sonar.api.ScannerSide`. (see https://docs.sonarqube.org/display/DEV/API+Changes)
However, injections of both annotations differ, for example does the new annotation not inject a `JavaResourceLocator` anymore and, therefore, have to refactor the need of it on the scanner side to be compatible with new APIs once the deprecated annotation is removed.

**Comment by beppo-sturmtief** [comment]
Hi,
this sounds already fixed, is that the case? The plugin is still marked incompatible for the current SQ release. If you have fixed the issue, would you mind updating the enty in the SQ plugin database?

And if it is still incompatible, can you estimate when it might be fixed?

Many thanks and kind regars,
beppo

**Comment by romani** [comment]
Issue is not fixed.
Latest release is compatible with 7.6 SQ, we use 7.6 in our CI https://github.com/checkstyle/sonar-checkstyle/blob/master/.circleci/config.yml#L5

Looks like we definitely need to update https://github.com/checkstyle/sonar-checkstyle/blob/master/README.md#description--features to have SQ version as interval from-to.

**Comment by beppo-sturmtief** [comment]
SQ7.7 was added today to the version matrix (https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix)

But the matrix lists CheckStyle plugin as not compatible with SQ 7.6 - and our 7.6 does not offer the plugin to install. Is it compatible with SQ7.6 as you stated? Can you encourage the SQ people to update the matrix?

Kind regards,
Beppo

**Comment by romani** [comment]
7.6 support is released at 4.18 plugin version, it didn't come to SQ please plugin central yet, it will be there at the end of this week , for reference follow https://community.sonarsource.com/t/rff-checkstyle-plugin-4-18/7576
If you want to get it quicker, download plugin at our github releases page.

**Comment by beppo-sturmtief** [comment]
Hi, on the page you linked, you state compatibility with SQ 6.7 - this is probably mixed up numbers?

Just for upgrade planning - any indicatiin about schedule for 7.7 support?

**Comment by romani** [comment]
please test plugin 4.18 it on SQ 7.7 and let us know, if doesnot work, please create new issue.

**Comment by charlesfendt** [comment]
I just tested... and the plugin 4.18 crash on SQ 7.7...
I opened a ticket: https://github.com/checkstyle/sonar-checkstyle/issues/208
