### ISSUE TITLE
SonarQube marketplace shows Checkstyle 4.11 as the latest version

### ISSUE THREAD

**Issue by freeWilly89** [checkstyle/sonar-checkstyle#195]
Sonar version: 7.1
Checkstyle sonar plugin verson: 4.11

Similiar issue as in #139.  Latest released Checkstyle Plugin version is not available via the sonar qube plugin marketplace. Currently only version 4.11 is there available.

Could you please update the marketplace listing?

**Comment by romani** [comment]
Unfortunately we do not control marketplace listing.

 Each upgrade to new version of checkstyle result in new release, it is special issue like https://github.com/checkstyle/sonar-checkstyle/issues/189 , there you can find links with our requests to be published to marketplace.
https://community.sonarsource.com/t/new-release-checkstyle-plugin-4-17/6767

Please ask this question at sonarqube site thread related to release.
