### ISSUE TITLE
Introduce tabWidth to Checker

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/sonar-checkstyle#206]
As per #204 and the corresponding changeset in CS (https://github.com/checkstyle/checkstyle/issues/6485), we have to add the property `tabWidth` to all checks and update the translations as well.

**Comment by rnveach** [comment]
@muhlba91 @romani This issue might be more then adding tab width as a property.
I believe it also affects the cardinality of modules as now almost every module will get an extra property and modules with 2 or more properties need a cardinality of `MULTIPLE`.
See rules of cardinality at https://github.com/checkstyle/sonar-checkstyle/issues/87/

**Comment by muhlba91** [comment]
huch. OK, I have added the property to all checks for now. Next, I‘ll add the cardinality to all checks having 2 or more properties. Is there anything special to consider despite adding the cardinality?

**Comment by rnveach** [comment]
Rules of cardinality are at #87 . I can't think of anything else that would be special for this issue.

I don't remember how changing the cardinality affected existing configurations on an upgrade. @romani can confirm, it may just require this issue to be labeled breaking compatibility if they have to re-add the rule.

**Comment by muhlba91** [comment]
Are we sure that those rules are up to date - can you please check `HeaderCheck` or `AnnotationUseStyleCheck` or `JavaNCSSCheck`? I found those just in the beginning of the file `rules.xml` and they do not have a cardinality set although having more than 2 properties.
Should we adapt all checks to the rule of having a cardinality of `MULTIPLE` if the check has more than 2 properties?

**Comment by muhlba91** [comment]
Personally, I agrre with @romani that having this property configurable on all checks is some kind of overload for the user. Most certainly you have one style per project at least and would not want to have the need of changing all rules to apply a different value than the default one. That's gonna be painful.
So, imo, having a use case where the `tabWidth` has a need to change for one rule to the other within the same project is quite rare.

Also, I agree with @rnveach that `tabWidth` might not be something affecting the cardinality. What do I gain when being able to specify the same rule with different widths? Most certainly one of them will report wrong information. The only place where I can think of it making a bit of sense is when you can specify some kind of path/file inclusion/exclusions for a rule. Then you could define e.g. files ending with `_4spaces` have this width and other don't. However, the question is how much sense such a configuration makes and whether it's not a rare case again.

Anyhow, despite that the question is rather what's the main purpose behind this change. You have added `tabWidth` to all checks and not as kind of a "global" property defined in the Checker configuration. Hence, if I only look at the implementation/definition I'd assume it's a property I have to or can set on every check and was designed like this.
Overall, it's a design decision if we should stick to the design of the main CS project and try keeping it on-par as good as possible or introduce a different design of splitting out properties and doing some "magic" in the background to transform ours to the CS design.

So the question is rather we follow design decisions of the main CS project (=introduce `tabWidth` to all checks) or introduce/follow our owns and question what's more useful and less painful for the user (=introduce `tabWidth` as a global property). If we go for a global property, shouldn't we remove the `tabWidth` in the current 2 checks where it's possible to set them to remove any confusion?

**Comment by rnveach** [comment]
> So the question is rather we follow design decisions of the main CS project 

Also, if this is such a big issue, why do we make this decision in main project. This doesn't have to be a customizable property by the user. If we just rename the setter to something else, then no other module but Checker can set it.

**Comment by muhlba91** [comment]
OK, well. Does anyone see a use case where `tabWidth` shouldn't be only set through the Checker?
If not, what about introducing the `tabWidth` to the Checker XML "only" because then it would also simplify any process for the user: no need to adapt `tabWidth` for every check and no "magic" happening in the background adding `tabWidth` automatically to each check based on a field in the config? Hence, the user just has to set it in the provided Checker XML - we can add the default value there s.t. it's visible to the user - and all works without confusion.
@romani @rnveach Would this be a feasible change in the main project? Then we can also not implement this issue but rather apply a change later to change the default Checker configuration and possibly also remove `tabWidth` from the current two checks?

**Comment by rnveach** [comment]
> and no "magic" happening in the background adding tabWidth automatically to each check

`magic` has to happen in main repo as logging violations is in AbstractCheck and we need the position to create the log message. @romani doesn't want checks to have instance to Checker, so we must have a field that Checker passes to the AbstractCheck.

> Would this be a feasible change in the main project? Then we can also not implement this issue but rather apply a change later to change the default Checker configuration and possibly also remove tabWidth from the current two checks?

This is what I was suggesting in my previous post and @romani was slightly suggesting asking if there was some global place where user's can specify tabWidth for Checker.
If you can do this in sonar, then lets go that way and I will create a new issue in main project.

So in sonar:
1) remove all references to tabWidth in any checks (re-examine their cardinality)
2) create a new dialog (or some form entry) where users can enter in their preferred tabWidth for Checker
3) Apply this new dialog's value to the XML that Sonar generates and passes to Checkstyle

**Comment by muhlba91** [comment]
Perfect, then we go this way. Hence, a new field in Sonar config for this property plus adding it automatically to each check when generating the XML. :)

**Comment by rnveach** [comment]
> plus adding it automatically to each check when generating the XML

This part isn't needed. Once tabWidth is given to Checker, Checkstyle automatically passes it to everyone else.

**Comment by muhlba91** [comment]
@rnveach sure, I meant append it to the Checker XML.
My idea is to append this property after the Checker Filters defined in the UI with `<property name="tabWidth" value="VALUE"/>`, hence by default resulting in appending to the Checker:
```
<module name="SuppressWarningsFilter" />
<property name="tabWidth" value="8"/>
```
