### ISSUE TITLE
False positive using GenericWhitespaceCheck

### ISSUE THREAD

**Issue by softdays** [checkstyle/sonar-checkstyle#21]
Context: SQ 5.6.1 LTS and CheckStyle plugin 2.4

Here is a false positive issue using GenericWhitespaceCheck and generics syntax:
![2016-08-29 15_14_50-composant securite extension habilitation](https://cloud.githubusercontent.com/assets/948293/18052635/cb41303a-6dfb-11e6-980c-aa5b3c0a9881.png)*

**Comment by romani** [comment]
please report issues on checkstyle project - https://github.com/checkstyle/checkstyle/issues
Sonar plug do nothing addition except for integration of validation to Sonar system
