### ISSUE TITLE
update public name in all xml DOCTYPEs 

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#212]
we have code like:
```
<!DOCTYPE suppressions PUBLIC
	    "-//Puppy Crawl//DTD Suppressions 1.1//EN"
	    "https://checkstyle.org/dtds/suppressions_1_1.dtd">
```

there should be no `Puppy Crawl`.

It should be like:
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L2
`"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"`

**Comment by muhlba91** [comment]
i did not find any such reference anymore. closing this.
