### ISSUE TITLE
Sonar 5.3 - Can not execute Checkstyle: cannot initialize  module TreeWalker Token "LPAREN" was not found in Acceptable tokens list

### ISSUE THREAD

**Issue by cdossantos** [checkstyle/sonar-checkstyle#23]
Hello,

I have to upgrade from Sonar 5.1 to Sonar 5.3 do to this issue https://jira.sonarsource.com/browse/SONAR-7008
But then I got this error from sonar-checkstyle 5.2:
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project xg-im-aggregator: Can not execute Checkstyle: cannot initialize
 module TreeWalker - Token "LPAREN" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck 

I'm using Sonar 5.3, sonar-maven-plugin 3.0.2 and sonar-checkstyle 5.2

Any ideas,

Thanks in advance

**Comment by tsjensen** [comment]
Are you sure about the sonar-checkstyle version number? Because I think it never went above 3.1 as of yet.

**Comment by cdossantos** [comment]
Hi,

You are right, the sonar-checkstyle plugin version is 2.4.

Regards

**Comment by romani** [comment]
http://checkstyle.sourceforge.net/config_whitespace.html#ParenPad

does not have LPAREN as allowed token.
please open issue for checkstyle project (https://github.com/checkstyle/checkstyle/issues) - describe why you need this.
