### ISSUE TITLE
Javadoc Method listed twice

### ISSUE THREAD

**Issue by Roemer** [checkstyle/sonar-checkstyle#235]
Sonar version: 7.9
Checkstyle sonar plugin verson: 4.21

Steps to reproduce or description of problem:
`Javadoc Method` ist listed twice. One should probably be named `Missing Javadoc Method`.
![image](https://user-images.githubusercontent.com/393641/61523659-18e1d800-aa15-11e9-9806-64e8e19d5864.png)

Another small typo is that `Member Name` is displayed as `Member name`.

**Comment by rnveach** [comment]
It is confirmed:
https://github.com/checkstyle/sonar-checkstyle/blob/6d544f56b0a61523bab31ab28c26a30432da751e/src/main/resources/org/sonar/l10n/checkstyle.properties#L100

**Comment by muhlba91** [comment]
fixed with #276 and will be included in the next release
