### ISSUE TITLE
TodoComment is missing

### ISSUE THREAD

**Issue by Roemer** [checkstyle/sonar-checkstyle#236]
Sonar version: 7.9
Checkstyle sonar plugin verson: 4.21

There is no rule for TodoComment. Can it be replaced with a `Regex` Rule, but how can I activate `Comments only` in a Regex rule then?

**Comment by rnveach** [comment]
@romani There is a item for it in the file.
https://github.com/checkstyle/sonar-checkstyle/blob/6d544f56b0a61523bab31ab28c26a30432da751e/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L1536
Are we sure it isn't showing up in the screens anywhere?

**Comment by romani** [comment]
Only screenshot of search can prove it, I need to find keyboard time to check this.

**Comment by Roemer** [comment]
Ah I always searched for `todo` and similar. It can be found under `Comment pattern matcher` so I will close this issue.

**Comment by romani** [comment]
It is very natural search by 'todo' we probably need to put such word in metadata ( I man not sure why is missed)
