### ISSUE TITLE
LowerCaseLongSuffixCheck is missed

### ISSUE THREAD

**Issue by vladimir-shulga** [checkstyle/sonar-checkstyle#24]
Upper Ell rule is specified as deprecated. It's recommended to use LowerCaseLongSuffixCheck instead but it isn't found in rules list.
<img width="1231" alt="screen shot 2016-10-24 at 2 50 29 pm" src="https://cloud.githubusercontent.com/assets/15751157/19679080/1f7f658e-9aa9-11e6-8da9-88096884ddf5.png">

After pressing LowerCaseLongSuffixCheck link rule isn't found and empty page is shown.
<img width="1178" alt="screen shot 2016-10-24 at 2 53 07 pm" src="https://cloud.githubusercontent.com/assets/15751157/19679092/3495681a-9aa9-11e6-8b3b-16b7dc57ed69.png">

**Comment by romani** [comment]
Checkstyle does not have LowerCaseLongSuffixCheck - 
http://checkstyle.sourceforge.net/checks.html

It might be from sonar itself.

http://checkstyle.sourceforge.net/config_misc.html#UpperEll is not deprecated, it is sonar team mark it by this label if they has similar(might not be the same) rule.

Sonar team marked as deprecated many rules, but their sonar analogs are offen a bit different by functionality.

I am closing issue as nothing to fix.
