### ISSUE TITLE
SonarCloud upcoming change: "sonar.organization" property soon mandatory

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#251]
Hello,

I'm Fabrice, from SonarCloud team at SonarSource.​

I am contacting you to notify you in advance of a change that will happen before the end of the year on SonarCloud: the​ "sonar.organization" property will become mandatory.​

Since you are one of the early adopters of SonarCloud, your project still belongs to the "Attic" organization - which was originally the only organization on SonarCloud when we started the service. Because of this, until now, you did not have to specify​ the​ "sonar.organization" property on your project since it was defaulting to the "Attic" org. For consistency reasons, we are going to make this property mandatory, which means that you will have to set it to "default". For instance:
if you are using Maven, this would look like the following in​ your main POM file:
<properties>
​ <sonar.organization>default</sonar.organization>
</properties>
If you are relying on the scanner CLI, you should add the following line in your "sonar-project.properties":
sonar.organization=default

You probably want to update your repositories as soon as possible to avoid any failure on your CI jobs when we make this property mandatory.

Note that an alternative is to delete your project from this "Attic" org and to follow the "Get started with GitHub" doc​ to have your project correctly setup on SonarCloud. You will lose history, but this is definitely a better option since this will allow you to benefit from all the latest features (including the analysis of Pull Requests).

May you have any questions, the​ SonarCloud forum​ is here to help you.

**Comment by romani** [comment]
@muhlba91 , please help to address this

**Comment by muhlba91** [comment]
Do we, in any way, depend on the history?
If not, I‘d suggest to go forward with option 2 to recreate the project with the correct group? :)

**Comment by romani** [comment]
https://github.com/checkstyle/sonar-checkstyle/blob/faefbf4354e4daca979d3ce4944a3457e93d7dc8/travis.sh#L18

We use such property during deploy.
We already have `<groupId>com.github.checkstyle</groupId>` so no relationship to sonarqube company at all

**Comment by romani** [comment]
I asked question at sonarqube forum https://community.sonarsource.com/t/checkstyle-sonarcloud-upcoming-change-sonar-organization-property-soon-mandatory/16315

**Comment by romani** [comment]
Nothing should be done, see details in forum
