### ISSUE TITLE
Many exceptions: Unable to find class for com.puppycrawl.tools.checkstyle.checks.naming.FileLength logged with checkstyle plugin 2.6

### ISSUE THREAD

**Issue by Phil-Jean** [checkstyle/sonar-checkstyle#26]
Hello,

Since the upgrade to Sonarqube 5.6 and the usage of the checkstyle plugin 2.6, many exceptions are logged related to a missing class:

[DEBUG] 09:28:07.898 Keep looking, ignoring exception
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find class for com.puppycrawl.tools.checkstyle.checks.modifier.FileLength
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createObject(PackageObjectFactory.java:133) [checkstyle-all-2.4.jar:na]

Have you an idea from where that comes?

Thanks,

Philippe

**Comment by romani** [comment]
yes, sorry about this bad design ...
Please ignore this, it is not a problem, by design, it is stupid brute force to find class in ClassLoader.

real issue is in checkstyle library - checkstyle/checkstyle#3184 . We will fix it in next release.
