### ISSUE TITLE
use Sonarqube.io for code verification from wercker

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#262]
based on experience and code of https://github.com/checkstyle/checkstyle/issues/5604
do same in this repo.

**Comment by romani** [comment]
new protected variable is created - https://app.wercker.com/checkstyle/sonar-checkstyle/environment

![image](https://user-images.githubusercontent.com/812984/72652901-84155400-393d-11ea-895c-e83f01370fb3.png)

**Comment by muhlba91** [comment]
@romani is this fixed now?

**Comment by romani** [comment]
Fix is merged
