### ISSUE TITLE
Apply checkstyle verification for 'it' sources

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#269]
from https://github.com/checkstyle/sonar-checkstyle/pull/258#discussion_r365800709

for some reason out `it` sources are not validated by checkstyle config. This need to be fixed.

**Comment by muhlba91** [comment]
can you verify that the normal test sources are validated?
i cannot get a failure if i change any test file to either violate the line length or import order which fails immediately for any source file in 'src/main/java' .
