### ISSUE TITLE
Is it possible to directly use the existing checkstyle.xml file with this plugin?

### ISSUE THREAD

**Issue by durgaswaroop** [checkstyle/sonar-checkstyle#27]
I have an existing checkstyle plugin with several style checks. Is there a way I can use that, in the sonarqube analysis instead of manually configuring the rules?

**Comment by romani** [comment]
I do not know too how to do this , related question #25 .

**Comment by durgaswaroop** [comment]
Ok. Can you tell me what this plugin does  It is not at all obvious from the Readme file.

**Comment by romani** [comment]
This Plugin add to Sonar all validation rules from Checkstyle

**Comment by durgaswaroop** [comment]
Yeah. So where does it get the rules of checkstyle from? The checkstyle rules are usually defined in a xml file. So, how can I get those rules in this plugin?

**Comment by romani** [comment]
after plugin intallation , All Checks are inside sonar 
https://raw.githubusercontent.com/checkstyle/resources/master/img/sonar-in-docker.PNG

**Comment by durgaswaroop** [comment]
Yeah but where are those checks configured? The checks file should be there somewhere, doesn't it?

**Comment by romani** [comment]
for now configuration should be done manually again in sonar.
No way to reuse import existing config file automatically.

**Comment by durgaswaroop** [comment]
Now, I am confused about what this plugin does. If we have to configure in Sonar anyway, I can do it directly without this plugin. Can't I?

**Comment by romani** [comment]
without plugin you will not see/find checkstyle rules at all.

**Comment by durgaswaroop** [comment]
But Sonarqube already has checkstyle builtin.

**Comment by romani** [comment]
It is true  for old versions of sonarqube.
It was buildin due to usage of this plugin. This plugin was developed by sonar team and only recently moved to support by community.

**Comment by romani** [comment]
Sonar config could be imported to Sonar during new profile creation - https://github.com/checkstyle/sonar-checkstyle/wiki/How-to-import-existing-checkstyle-config-to-sonar

**Comment by durgaswaroop** [comment]
Thanks. I will try that out.
