### ISSUE TITLE
Send jacoco code coverage to sonarqube.io during verification

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#270]
from https://github.com/checkstyle/sonar-checkstyle/pull/258#issuecomment-576152626

we need to point sonarqube where to get code coverage(jacoco). 
This is blocker for release, as without code coverage we will not be accepted in plugin center.

**Comment by romani** [comment]
@muhlba91 , we need to update https://github.com/checkstyle/sonar-checkstyle/blob/master/.ci/wercker.sh#L35 to give sonar path to jacoco report.
it might need simply to use this variable - https://docs.sonarqube.org/display/PLUG/JaCoCo+Plugin

**Comment by muhlba91** [comment]
@romani is this fixed now?

**Comment by romani** [comment]
Fix is merged
