### ISSUE TITLE
New metadata maintanence method: Fetch directly from checkstyle

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/sonar-checkstyle#317]
This issue is to keep track of:

- [x] Using library from checkstyle JAR instead of separate JAR

- [x] Remove/modification of UTs(e.g. `ChecksTest`) and other steps to facilate the new release process.

**Comment by romani** [comment]
>  Remove/modification of UTs(e.g. ChecksTest) and other steps to facilate the new release process.

@gaurabdg ,
please clarify what we planned to do with this

**Comment by gaurabdg** [comment]
@romani This meant the modification of UTs which validated metadata of modules. It was done in the PR you merged, as discussed, by adding a pre checkstyle 8.36 module list.

**Comment by romani** [comment]
Ok, I am closing this issue
