### ISSUE TITLE
create docker image for testing of sonar plugin

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#32]
We need to combine:
https://hub.docker.com/_/sonarqube/
ubuntu+maven+jdk8+git
to create new public image for hub.docker.com owned by checkstyle organization.

to adjust wercker CI to use it as base system.
In that system we need to:
1) clone sonar-checkstyle sources
2) package all
3) install in sonar
4) restart sonar
5) make sure sonar is starting
6) do test launch of "mvn sonar:sonar"  against sonar-checkstyle sources. No errors are expected.

**Comment by romani** [comment]
Git in docker - https://github.com/kr1sp1n/docker-git/blob/master/Dockerfile

**Comment by romani** [comment]
restart of sonar:
`curl -X POST http://localhost:9000/api/system/restart -u admin:admin`

**Comment by MEZk** [comment]
@romani 
Might be useful
https://github.com/spotify/docker-maven-plugin

**Comment by romani** [comment]
pushing to docker hub - https://docs.docker.com/docker-hub/repos/

**Comment by romani** [comment]
done , example of failure - https://app.wercker.com/checkstyle/sonar-checkstyle/runs/build/58abc664e560360100d6bc74?step=58abc66ad2fd510001653fcb

for now docker image will be hosted in my private user, as it become stable I will move it to "checkstyle" user.

**Comment by romani** [comment]
image - https://hub.docker.com/r/romani/sonarqube-maven-git/

**Comment by romani** [comment]
side note:
I failed to install "less" tool to docker. Package is easy to install, package "less", but during to launch it is failing with "WARNING: terminal is not fully functional".
