### ISSUE TITLE
remove all old format metadata files from repo

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#321]
as https://github.com/checkstyle/sonar-checkstyle/pull/318 merged

we need to remove all old files from repo.
We need to keep only few modules old files as test/resources to be able to load them by tests only.

Files to be removed (attention to keep compatibility we still need some files like this test/resources to be sure we can load data from them, as all exists extensions unlikely to update to new medata format in near future):
![Sonar-resources-to-remove](https://user-images.githubusercontent.com/812984/91647249-5c2aba80-ea0d-11ea-9d02-85f1d4320eab.png)

**Comment by muhlba91** [comment]
@gaurabdg please focus on #322 first, then this issue.

**Comment by muhlba91** [comment]
@romani @rnveach was this not done by #379?

**Comment by rnveach** [comment]
I probably created a duplicate issue when I worked on the previous things.

I agree this issue looks done on face value, but I assume the screenshot is trying to show the files that are to be removed. `checkstyle-model` and `checkstyle-plugin` still remain in the repo after the other mentioned issue.

They no longer contain any information related to modules but still contain other information. Someone else more familiar with that information would need to determine if they could be removed or if they still serve a purpose that can be removed.

**Comment by romani** [comment]
They were left to keep backward compatibility, to make sure we keep loading them in third-party extension like sevntu.

Ideally we can:
Remove all
Keep in test area only few to remember how they look like, to keep compatibility  for a bit more.

**Comment by rnveach** [comment]
@romani All backwards compatibility was removed when the other issue was completed. Nothing remains of old loading behavior.

**Comment by romani** [comment]
I am ok to remove such files.

@muhlba91 , please confirm that you agree.

**Comment by muhlba91** [comment]
i agree, keeping old stuff with not much purpose does not bring value and will start confusing someone.

**Comment by muhlba91** [comment]
i believe this is fixed already once we transitioned entirely to the new mechanism via metadata. i do not see such old files anymore - closing this.

**Comment by rnveach** [comment]
> checkstyle-model and checkstyle-plugin 

These still remain as I mentioned. They were mentioned in this first post, but I am not sure if need to be removed or how to say they are still valid.
