### ISSUE TITLE
after 8.36 update we missing validation on basic types

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#322]
in code base after update to 8.36  
create new rule for "Abbreviation As Word In Name" make any  boolean value to be "1111"
Detected: no violation, config is saved
Expected: violation and dialog window should not allow to save config.

Attention in PR please test all other basic types and share screenshots with violations. Please also test regexp.

in 8.33 we did:
![Screenshot from 2020-08-29 17-08-01](https://user-images.githubusercontent.com/812984/91648302-b8e0a200-ea1a-11ea-9f21-b537a63202da.png)

**Comment by romani** [comment]
@gaurabdg , 
http://javadocs.sonarsource.org/latest/apidocs/org/sonar/api/server/rule/RuleParamType.html
Please add support of float , checkstyle do support it.
https://checkstyle.org/property_types.html
Please review other similar types.

**Comment by muhlba91** [comment]
@gaurabdg do we have a lead on the bool issue?

**Comment by gaurabdg** [comment]
> @gaurabdg do we have a lead on the bool issue?

It is merged https://github.com/checkstyle/sonar-checkstyle/pull/325.
