### ISSUE TITLE
java.lang.IllegalStateException: Can not execute Checkstyle with Sonar V8.4

### ISSUE THREAD

**Issue by gsepsupport** [checkstyle/sonar-checkstyle#334]
Hi Team,

After upgrade Sonar 8.4 and checkstyle 8.35, we are facing a blocker issue while running sonar analysis for java code using Jenkins Job.

Sonar analysis is failing to analysis the files which are contain German chars: i.e a – ä, o – ö, u – ü, au – äu.

We never faced this kind of issues with earlier version of plugin.

Sonar version: Enterprise Edition Version 8.4.1 (build 35646)

Checkstyle sonar plugin version: 8.35

Please let us know if you need any further details and provide the solution.

Logs:
17:21:55 13:51:55.826 ERROR: Error during SonarQube Scanner execution
17:21:55 java.lang.IllegalStateException: Can not execute Checkstyle
17:21:55 	at org.sonar.plugins.checkstyle.CheckstyleExecutor.executeWithClassLoader(CheckstyleExecutor.java:110)
17:21:55 	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:78)
17:21:55 	at org.sonar.plugins.checkstyle.CheckstyleSensor.execute(CheckstyleSensor.java:42)
17:21:55 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
17:21:55 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
17:21:55 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
17:21:55 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
17:21:55 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
17:21:55 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
17:21:55 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
17:21:55 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
17:21:55 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:388)
17:21:55 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:384)
17:21:55 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:353)
17:21:55 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
17:21:55 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
17:21:55 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
17:21:55 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
17:21:55 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
17:21:55 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
17:21:55 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
17:21:55 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
17:21:55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:21:55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
17:21:55 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
17:21:55 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
17:21:55 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
17:21:55 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
17:21:55 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
17:21:55 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
17:21:55 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
17:21:55 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
17:21:55 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by muhlba91** [comment]
i have tried adding a special character in my source files:
- 8.35: working for me
- 8.36.1 (next release): working for me

test code:
```
package com.acme;

// comment with ä and ß
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
```
configuration of CS: all rules enabled with default configuration, except for template rules
file encoding: unicode / utf-8

can you please reproduce your problem with a simple project. i usually use https://github.com/SonarSource/sonar-scanning-examples (in particular: sonarqube-scanner-gradle) and modify/add source files accordingly.

**Comment by romani** [comment]
> Sonar analysis is failing to analysis the files which are contain German chars: i.e a – ä, o – ö, u – ü, au – äu.

https://checkstyle.org/writingchecks.html#Limitations
`Java code should be written with ASCII characters only, no UTF-8 support.` UTF is supported in comments and string values, but not in identifiers of java code.
https://github.com/checkstyle/checkstyle/issues?q=is%3Aissue+is%3Aopen+utf

**Comment by muhlba91** [comment]
@gsepsupport will close this issue now. please reopen if necessary.
