### ISSUE TITLE
Old Issues raised as New Issues

### ISSUE THREAD

**Issue by rupreck** [checkstyle/sonar-checkstyle#337]
Sonar version: [8.2]
Checkstyle sonar plugin version: [4.30]

The two rules:
1. Custom Import Order (checkstyle:com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck)
2. Import Order (checkstyle:com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck)

Both raise old issues as new issues after the first run following the baseline analysis.

**Comment by romani** [comment]
We do not control history of violations, checkstyle always do validation on whole code and report all violations. 
There might be some issues in Sonar or something is changed in violation message.
But I do not see what could cause it https://checkstyle.org/releasenotes.html

**Comment by muhlba91** [comment]
@rupreck issue will be closed now. please reopen if necessary.
