### ISSUE TITLE
Import google_checks.xml config to sonar

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#34]
Problem is like this on 3.1 version of plugin, Soanr Version 6.1

Rule template can't be activated on a Quality profile

![sonar-checkstyle-google-import-problem](https://cloud.githubusercontent.com/assets/812984/21276096/c079496a-c384-11e6-9731-f459b61584a1.png)

**Comment by romani** [comment]
closed in favor of #2 .

**Comment by evenh** [comment]
I sitll experience the same when running sonar-checkstyle 3.5 on SonarQube 6.2

**Comment by travistrle** [comment]
I still have the same issue.

**Comment by diegolovison** [comment]
I still have the same issue.

**Comment by romani** [comment]
this issue is closed as duplicate of #2 , if you want to share your feedback - please to your +1 at #2
