### ISSUE TITLE
version bumped to 8.X

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#344]
Why version is upgraded from 4.34 to 8.35 ?
 https://github.com/checkstyle/sonar-checkstyle/commit/c53befb21b10a2354afb9006092f51375c6a1162#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R7

**Comment by muhlba91** [comment]
With 8.35 we introduced the new metadata and I wanted to make versioning equal to CS - at least for major and minor version numbers.
It was fitting with the metadata introduction as a new concept well enough to adapt running on the same version numbers as the main project.
