### ISSUE TITLE
Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.FileTabCharacterChecktemplate

### ISSUE THREAD

**Issue by slin1972** [checkstyle/sonar-checkstyle#356]
SonarQube version: [8.0.0.29455]
Checkstyle sonar plugin version: [8.39]

I also tested it on the SonarQuebe8.6 and Checkstyle sonar plugin 8.40

1. Exception when i create one profiles and use [google_checks.xml](https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.39/src/main/resources/google_checks.xml)

![image](https://user-images.githubusercontent.com/7867412/108704986-ad90ae00-7547-11eb-8da7-92201e595cc0.png)

**Comment by slin1972** [comment]
A lot of rules can't be actived when i try modify checkstyle content.
such as <module name="UnusedImports" />

**Comment by slin1972** [comment]
I need help, please

**Comment by slin1972** [comment]
@muhlba91

**Comment by muhlba91** [comment]
first, @slin1972 could you please provide SQ log output as well?

second, @romani i remember there are some special cases with importing rules from an xml file? could you elaborate on it, please?

third, i believe regarding the import functionality (apart from the second point) could be affected by a bug related to template rules. assuming i take the `Indentation` check out of the xml now. this will be, according to the metadata and properties provided a template rule in SQ. however, a template rule in SQ is an instance of the `IndentationCheck` with a name, description, etc. and the property values for this check. I doubt SQ can infer all this information from the xml provided to auto-generate an instance of a template, assign it to a quality profile and activate it successfully.
however, please note that this is an observation with no proof/check - @romani any further thoughts on that? i actually start considering deprecating the import feature, especially if a CS xml cannot be used anyways and if the second point mentioned above applies to that we have some restrictions there.

@slin1972 for the moment, please provide the log output requested above for completeness and data points.
however, at the moment, i suggest to create the checks manually in SQ depending on your particular needs for each of them. i would also suggest you to use the new template rules - this means if you search for a specific check in SQ, you most likely will find 2 checks with the same(/similar) name and one of them will be marked as "template" in SQ. please use this one! the other one (non template) will be phased out in the future.

**Comment by romani** [comment]
@muhlba91 , for templates we do not support imports - https://github.com/checkstyle/sonar-checkstyle/issues/2
it is old and very awaited feature of plugin.

**Comment by slin1972** [comment]
@muhlba91 SQ not have any new log when i commit new profiles request.
and i set sonar.log.leve l=DEBUG

i think you can try the question.

I think this feature is very useful and I don't want to manually activate it one by one.

**Comment by slin1972** [comment]
@muhlba91

**Comment by slin1972** [comment]
I've entered them one by one, so i close the issue now.

**Comment by hwacookie** [comment]
> I've entered them one by one, so i close the issue now.

I feared you would write this at the end of the thread.

Sonarqube, it is really a pity that we have to re-create all settings manually now. Sigh!
