### ISSUE TITLE
getting checkstyle error while code scanning

### ISSUE THREAD

**Issue by rohitjalal** [checkstyle/sonar-checkstyle#359]
Sonar version: 7.9.4
Checkstyle sonar plugin version: 4.21

getting error though no checkstyle rules are activated,kindly help.

Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/jenkins/workspace/OSS/UIV/UIV_CI/UIV-AUTOMATION/SonarQube/sonarqube_analysis_iHub/iHub/ihub-datagrid-archetype/src/main/resources/archetype-resources/src/main/java/component/__datagridName__Grid.java

15:35:13  Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/jenkins/workspace/OSS/UIV/UIV_CI/UIV-AUTOMATION/SonarQube/sonarqube_analysis_iHub/iHub/ihub-datagrid-archetype/src/main/resources/archetype-resources/src/main/java/component/__datagridName__Grid.java.
15:35:13  	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
15:35:13  	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:160)
15:35:13  	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
15:35:13  	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
15:35:13  	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)

**Comment by romani** [comment]
checkstyle.JavaParser.parse

ihub-datagrid-archetype/src/main/resources/archetype-resources/src/main/java/component/__datagridName__Grid.java

Please recheck that this file is compilable.

If compilable, please file issue on library https://github.com/checkstyle/checkstyle/issues
