### ISSUE TITLE
Error message not readable

### ISSUE THREAD

**Issue by hwacookie** [checkstyle/sonar-checkstyle#360]
Sonar version:  8.4.2.36762

Checkstyle sonar plugin version: 8.4

Steps to reproduce or description of problem:

1) Create a new Quality Profile for Java that includes Checkstyle-Settings
2) Try to import the checkstyle settings .xml file 

The import will fail because checkstyle rule templates cannot be imported anymore, unfortunatly ((see https://github.com/checkstyle/sonar-checkstyle/issues/356)

But in addition to that, one can also not read the error message that pops up which could be helpful to filter out all the settings that cannot be imported. See screenshot below:

![image](https://user-images.githubusercontent.com/880808/112645838-2e90dd00-8e47-11eb-8bb2-23f18ceaab25.png)

**Comment by romani** [comment]
I doubt plugin have ability to extend message in sonar.
Inspection in browser is only way to see it

**Comment by hwacookie** [comment]
Then this should be fixed in sonar itself, or the plugin should maybe use some other way to communicate with the user. As it stands right now, the error message is not really helpful.

**Comment by muhlba91** [comment]
closing issue as stale - this is related to sonar itself, and import is not yet supported either. please refer to #2. happy to reopen it if issue gets traction from other users.
