### ISSUE TITLE
Issues compiling/running in Eclipse

### ISSUE THREAD

**Issue by rnveach** [checkstyle/sonar-checkstyle#38]
Importing sonar-checkstyle as a maven project isn't very straightforward and I can't get it to fully work yet.
None of these issues prevent me from compiling/running with pure maven.
I am using Luna Service Release 2 (4.4.2) .

1)
When originally importing as a maven project and doing a build, 91 errors come up in `checkstyle-sonar-plugin`.
Ex: `AbstractCheck cannot be resolved to a type`
All errors are because the project can't find the original checkstyle dependency in `checkstyle-all`.

To fix this, I had to go to the build path of `checkstyle-all` and tell it to export the `Maven Dependencies`.
Even though this does remove the build errors, 10 junits still fail with the following exception: `java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/api/AuditListener`
I didn't get this error before f93efab69ee914d2f2458d2186cfc631f218a86b.
I have not found a full working solution.

2)
`checkstyle-sonar-plugin` imports with a compiler level of Java 1.7 class and `checkstyle-all` imports with a compiler level of Java 1.5.
Checkstyle is currently 1.8 and can't be used with an older JRE unless you use `checkstyle-backport-jre6`.
Before f93efab69ee914d2f2458d2186cfc631f218a86b , when I ran the junits specifically on a JDK7 I got minor/major version conflict. Had no issues running with a JDK8.

I did have a 3rd issue importing the project with main checkstyle project in the same workspace, but I believe it was fixed with b3ad0d0d383bb80920128ca3df4394b9f4f5d264.

**Comment by rnveach** [comment]
Point 2 is done only for `checkstyle-sonar-plugin` by commit e22f863bd387e936ffc4427329b0ad3588015e0d.
`checkstyle-all` still loads as Java 1.5.

**Comment by romani** [comment]
while eclipse have a problem with shaded jar usage :
![sonar-plugin-compile-in-eclipse](https://cloud.githubusercontent.com/assets/812984/21444175/eda5d360-c85f-11e6-9a00-a052e852448e.PNG)

**Comment by rnveach** [comment]
Shaded jar is not built by eclipse by default, `mvn package` has to be used, but fix does work.

Point 2 is completely fixed by 7b73e846d632005f77cff3cf2fd26e755c470609.

**Comment by romani** [comment]
@rnveach , I used Eclipse Neon 4.6.2 , imported all three projects (parent too) as maven projects, added checkstyle-all jar manually. All sources are compiled. UTs are running.

Can we close the issue ?
we could make a wiki page on how to import project to eclipse.

**Comment by rnveach** [comment]
@romani Making a wiki page and closing the issue is fine.

**Comment by rnveach** [comment]
Wiki is added.
https://github.com/checkstyle/sonar-checkstyle/wiki/sonar-checkstyle-with-Eclipse
