### ISSUE TITLE
Where is the tabwidth of the file length rule set in sonarquebe?

### ISSUE THREAD

**Issue by lkqm** [checkstyle/sonar-checkstyle#407]
Sonar version: 9.2.4
Checkstyle sonar plugin version: 10.0

Steps to reproduce or description of problem:

I upgrade sonarqube and install checkstyle plugin, when i set 'file length' rule not foud tabWidth, the default is 8, i want set to 4, Thanks.

**Comment by muhlba91** [comment]
hi,
`tabWidth` is set "globally" (in SQ or for a project) in the Checkstyle Checker configuration. open the configuration (of SQ or your project) and find the Java related configuration. in there you'll find the possibility to define `tabWidth`.
i hope this helps.

**Comment by lkqm** [comment]
Thanks, I found it.
