### ISSUE TITLE
Migrate all jobs from Wercker to Travis or any other CI

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#412]
Wercker will be shut down on oct 31 2022

we need to stop using it.
Move all to Travis or any other CI, main repo has bunch CI in use.

**Comment by muhlba91** [comment]
thanks for raising this!

is there any preference or main direction the main repo heads to?
i‘d like to keep it consistent if so; otherwise, i‘d go ahead to choose the more suitable one to move to from wercker.

**Comment by romani** [comment]
Choose any you want, you can look at available CIs in main repo.
