### ISSUE TITLE
activate Checkstyle and sevntu checks over sonar-checkstyle repository

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#45]
set of rules could be taken from checkstyle repo.

**Comment by rnveach** [comment]
@romani A lot of the violations have been fixed, but I can't do more without diving into the code for Javadocs, illegal catches, and import control.

**Comment by muhlba91** [comment]
@romani what's the status of this? i somehow see #217 as a follow up?

**Comment by romani** [comment]
Checkstyle is activated to keep code on leash.
Sevntu Checks can be applied in separate issue
