### ISSUE TITLE
Is sonar-checkstyle compatible with Sonarqube 10.x

### ISSUE THREAD

**Issue by ericrichtert** [checkstyle/sonar-checkstyle#479]
Sonar version: 9.9
Checkstyle sonar plugin version: latest

We want to upgrade to SQ 10.0, is sonar-checkstyle compatible with this version?

**Comment by romani** [comment]
@muhlba91 , please share details if you tested it

**Comment by muhlba91** [comment]
SQ 10.0 was released 6 days ago. no testing done as of yet.

i‘ll update once testing has been done - definitely not before easter.

**Comment by muhlba91** [comment]
i just tested the current version with SQ 10.0 and it works for me.
