### ISSUE TITLE
Make "sonar-checktyle" compatible with SonarQube 10.4 "DownloadOnlyWhenRequired" feature

### ISSUE THREAD

**Issue by agigleux** [checkstyle/sonar-checkstyle#499]
Hello,

I'm Alex, Product Manager at Sonar.

SonarQube 10.4 will come with a feature to only download plugins when they are required. When there are files corresponding to the language handled by the plugin, the plugin will be downloaded, otherwise, the plugin won't be downloaded. This is great to save network bandwidth and speed up the bootstrap of the scans.
This feature will be disabled by default to let the time to plugin maintainers to adjust their plugin. It will be activated by default with SonarQube 10.5

For plugins that have a dependency on a base analyzer provided by default with SonarQube, an additional property is required to be added to the MANIFEST of the plugin.
By doing so you will avoid being in this situation:
- sonar-checkstyle is downloaded because it doesn't support the new property so it is downloaded from the server at each scan
- sonar-java is not downloaded because there are no .java files in the repo to scan
- a NoClassDefFoundError is thrown

In order to avoid that you need to:
* upgrade sonar-packaging-maven-plugin to https://github.com/SonarSource/sonar-packaging-maven-plugin/releases/tag/1.22.0.705
* add `<requiredForLanguages>java</requiredForLanguages>`

**Comment by muhlba91** [comment]
thank you for this notice!
we'll try to include it in the next release to make sure we stay compatible with this new property.
