### ISSUE TITLE
[DOCU] Usage installation guide also for never versions of sonarqube (because it´s changed)

### ISSUE THREAD

**Issue by Raboro** [checkstyle/sonar-checkstyle#512]
Sonar version: Version 10.4.1
Checkstyle sonar plugin version: 10.14.2

In the README under Usage is the installation defined. But in never versions of sonarqube the UI changed. There is no Tab to install the plugin under System anymore. Could you please provide a more specific installation guide for never versions of the UI. Now it´s under Administration -> Marketplace

**Comment by muhlba91** [comment]
to avoid such issues in the future, i have updated the README to refer to the Sonar documentation on how to install a plugin. this will eliminate upcoming issues as well.
