### ISSUE TITLE
Duplicate Issues with Latest Version.

### ISSUE THREAD

**Issue by rupreck** [checkstyle/sonar-checkstyle#517]
Sonar version: 9.9.4 Enterprise
Checkstyle sonar plugin version: 10.14.2 

Steps to reproduce or description of problem:

Hello,

Updating from 10.9.3 caused maven java projects to show duplicate issues for every issue.  

Rolling back removed the problem.

Here are some examples.

<img width="830" alt="image" src="https://github.com/checkstyle/sonar-checkstyle/assets/3411358/3d14f5e7-f7e3-4d63-b72a-6a74315ed5b4">

and

<img width="855" alt="image" src="https://github.com/checkstyle/sonar-checkstyle/assets/3411358/ace02a49-8136-4e1c-85b6-2a8338c224a7">

This looks like a quite serious bug.

**Comment by muhlba91** [comment]
quick info: with the latest `master` branch, i do not get duplicates. i believe this was of the duplicate scope definition solved here: https://github.com/checkstyle/sonar-checkstyle/pull/514.

**Comment by muhlba91** [comment]
release PR on SQ side: https://github.com/SonarSource/sonar-update-center-properties/pull/534

**Comment by muhlba91** [comment]
@rupreck can you please confirm with `10.15.0` and update this issue? 😃

**Comment by rupreck** [comment]
Using 10.16.0 the problem remains.

<img width="827" alt="image" src="https://github.com/checkstyle/sonar-checkstyle/assets/3411358/c3cca396-54d3-4269-8757-031a00839707">

We again have to revert back to 10.9.3 again.

<img width="803" alt="image" src="https://github.com/checkstyle/sonar-checkstyle/assets/3411358/534bc532-0a67-4012-8095-518e20362bb3">

Will

**Comment by muhlba91** [comment]
could you also test `10.12.5` on whether this issue occurs?

there was a larger change removing deprecated sonarqube api from `10.12.5` to `10.14.1`. it would be good to know if this is related.

additionally, do you have a multi-module project? maybe #511 could be related to this then.

**Comment by rupreck** [comment]
This problem resurfaced in 10.16.0 when installed to SonarQube Enterprise 10.5.1, although not immediately on every analysis. It seems to have affected only 1 large legacy project

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/23117ae1-053a-47fb-a36f-0041d86c1654">

However it does not appear with the latest 10.17.0 and appears to be resolved now.
