### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by frankbenoit** [checkstyle/sonar-checkstyle#56]
Hi

the rule "Abbreviation As Word In Name", there is a link to the Google StyleGuide, which is no more working.
You may change the link to point to https://google.github.io/styleguide/javaguide.html

Frank

**Comment by rnveach** [comment]
I believe this is the link being described: https://github.com/checkstyle/sonar-checkstyle/blob/78b2bb55e69ecfad6946b0aba797d6ac6439f2f2/checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle/com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck.html

**Comment by romani** [comment]
bad link - http://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s5.3-camel-case
.... documentation blocks are out of sync from what we have in main repo ....

we need to do: 
1) fix this link
2) enforce linkcheck maven plugin on repo to ensure no dead links in that html files.
3) sync documentation text should be done in separate issue (complex problem)

**Comment by romani** [comment]
usage of linkcheck plugin is not possiblenow , new feature is requested - https://issues.apache.org/jira/browse/MLINKCHECK-27

Whole link of pages that have link some of them are dead:
```
~/java/github/checkstyle/sonar-checkstyle/checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle [master|✔] 
$ grep -l "http" *.html
com.puppycrawl.tools.checkstyle.checks.annotation.PackageAnnotationCheck.html
com.puppycrawl.tools.checkstyle.checks.AvoidEscapedUnicodeCharactersCheck.html
com.puppycrawl.tools.checkstyle.checks.design.OneTopLevelClassCheck.html
com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck.html
com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.html
com.puppycrawl.tools.checkstyle.checks.modifier.ModifierOrderCheck.html
com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck.html
com.puppycrawl.tools.checkstyle.checks.regexp.RegexpCheck.html
com.puppycrawl.tools.checkstyle.checks.UpperEllCheck.html
```

**Comment by romani** [comment]
all files with links are updated.

All other documentation updates should be done by #57 .
