### ISSUE TITLE
When I import the custom rules file with the number 50, the quality profile actived more than 100 rules

### ISSUE THREAD

**Issue by ZhaoAlice** [checkstyle/sonar-checkstyle#59]
Here is my environment : sonarqube 5.6.3  and sonar-checkstyle-plugin 2.4. The questions are following:

1. I create a quality profile with importing the custom rule file(.xml) that includes 50  rules for checkstyle, however, the quality profile contains and actives more than 100 rules, then I have to inactive the needless rules for me one by one. Is there other way just to active the rules included in my custom file ? 

2. The sonar-checkstyle-plugin 2.4 is corresponding to checkstyle 6.12.1, My custom rule file based on checkstyle 5.6, Is checkstyle downward compatibility ? 

3. When I use the quality profile above without the needless rules, the rule named WhitespaceAround judged the codes contain '<' , '>' and '?' error, example List<type> and List<?>. When I use the checkstyle plugin with eclipse, the above errors were not checked,  this brings the inconformity between the sonar-checkstyle-plugin and the checkstyle plugin with eclipse. I am confused how to resolve this problem. Do I have to use the lower version sonarqube 3.6, sonar-checkstyle-plugin 2.1.1 corresponding to checkstyle 5.6 used by the rules in my custom rule file ?  If so, I have to start all over. I have seen the  similar problem #14, whether or not the problem can be resoved if I upgrade sonar-checkstyle-plugin to 3.1 version.
 here are screenshots:
![image](https://cloud.githubusercontent.com/assets/23230757/21718069/c61eacbc-d44f-11e6-9470-94396066d351.png)
![image](https://cloud.githubusercontent.com/assets/23230757/21718465/a3a51420-d452-11e6-9aa3-533ace37f95f.png)

**Comment by rnveach** [comment]
> Is checkstyle downward compatibility ?

Minor versions *try* to be backward compatible, but major versions most likely break compatibility somewhere.
[ReleaseNotes for checkstyle](http://checkstyle.sourceforge.net/releasenotes.html) go back quite a few releases and should say where most backward compatibility is broken.

> the rule named WhitespaceAround judged the codes contain '<' , '>' and '?' error, example List and List<?>.

I would look to the rules/config you are using first.
The tokens you are referring to are `WILDCARD_TYPE, GENERIC_START, GENERIC_END`, and they are not enabled by default in [WhitespaceAround](http://checkstyle.sourceforge.net/config_whitespace.html#WhitespaceAround).
I could not produce any violations with the default module with regression on those older releases of checkstyle.

**Comment by romani** [comment]
>Is checkstyle downward compatibility ?

http://checkstyle.sourceforge.net/releasenotes.html

We did 17 releases that has breaking changes. We do not support not latest releases. Please try to upgrade.

> I have to inactive the needless rules for me one by one. Is there other way just to active the rules included in my custom file ?

Please upgrade to latest version of sonar and plugin, if still a problem please report separate issue with all details , the more the better.

>Do I have to use the lower version sonarqube 3.6, sonar-checkstyle-plugin 2.1.1 corresponding to checkstyle 5.6 used by the rules in my custom rule file ?

I did not tested that, but you can try.
I recommend to upgrade checkstyle to latest version. We did huge amount of fixes from 5.6 .

**Comment by ZhaoAlice** [comment]
@rnveach Thank you for your comments. I will read the [ReleaseNotes for checkstyle](url) carefully to solve my doubts about compatibility. I create the  WhitespaceAround rule by rule template with  WILDCARD_TYPE, GENERIC_START, GENERIC_END by default. I have removed the tokens from my custom rule manually. 
@romani Thank you for your comments. Due to the custom rules according to checkstyle 5.6 decided by team, I have no privilege to change, it's a pity that I can't upgrade to the latest releases.
I will try to  upgrade to latest version of sonar and plugin, I am not sure whether quality profile created by myself with the custom rules will be omitted, I have to evaluate workload. I am afraid I have to  start all over to remove the needless active rules one by one.

**Comment by romani** [comment]
You need to try, by using 5.6 you miss hundreds of bugfixes in existing Checks. 
Upgrade to new version will not trigger new Checks activation, so your config will stay the same.
It is possible that your will get more violations from checkstyle from existing Checks of your config.

Fyi: only from release 3.1(checkstyle 7.1) plugin is supported by checkstyle team. So behavior is more consistent is only recently.

You are always welcome to join us to make plugin better.
