### ISSUE TITLE
update documentation after transfer

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#6]
from email:

> looks like Sonar will not update http://dist.sonarsource.com/reports/coverage/checkstyle.html page.

About the coverage report, you really don't need to keep it up-to-date or provide your own report. Simply remove it! If the report is not up-to-date, it's our problem. It should be Sonarsource work to keep the tracking "alive", as an internal tool. From a pure Checkstyle perspective, and as the new official maintainer of the plugin, I would invite you to :
Remove the now useless part about the rules which have been rewritten from the README.md file, including the link to the report:
A majority of the Checkstyle rules have been rewritten in the Java plugin. Rewritten rules are marked "Deprecated" in the Checkstyle plugin, but a [concise summary of replaced rules](http://dist.sonarsource.com/reports/coverage/checkstyle.html) is available.
Remove all the "DEPRECATED" status tags from the rules in the rules.xml file: https://github.com/checkstyle/sonar-checkstyle/blob/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml
Update all the rules description to remove the links to the sonarsource rules in this folder: https://github.com/checkstyle/sonar-checkstyle/tree/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle
After all, you are now the rightful maintainer of the plugin, and I can't see why these rules should be marked as deprecated anymore. As the checkstyle plugin is not shipped anymore with SonarQube, a SonarQube user installing the checkstyle plugin won't be interested by having the mapping with the Sonarsource java rules.

I'm however pretty sure that if you could provide a list of rules from checkstyle wrongly mapped, someone at Sonarsource will be pretty happy. :)

Cheers,
Michael

**Comment by romani** [comment]
in case page of sonar-checkstyle mapping could disappear , backup is https://drive.google.com/open?id=0B3LUiB4ZPKNjalloQ0tEVl9tYmM

**Comment by romani** [comment]
from Michael:
> About the "deprecation" of rules, which is currently in place in the Checkstyle plugin (Checkstyle rules covered by SQ rules are marked as being Deprecated in favor of the corresponding SQ rule), it sounds totally natural to us that this aspect may be fully removed as soon as you take ownership. Your rules, your plugin, your choice! :)

we need to remove Deprecated

**Comment by romani** [comment]
deprecations were removed

**Comment by rnveach** [comment]
@romani If all rules should be `READY`, then we can add this to the UT in #28.
I skipped any fields I was unsure about what value should be set and this was one of them.

**Comment by romani** [comment]
it is ok to skip this, I decided to do substitution instead of removal for now just to simplify my way to release.
