### ISSUE TITLE
Change artifact name and provide deployment process

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#7]
we need to release this plugin with new group/name

location should be at
https://repo1.maven.org/maven2/com/github/

```
  <groupId>com.github.checkstyle</groupId>
  <artifactId>checkstyle-sonar-plugin</artifactId>
  <version>2.6-SNAPSHOT</version>
```

attention to artifactId name, it is done to follow names of https://github.com/sevntu-checkstyle/sevntu.checkstyle (maven plugins notation, first name is owner).

deployment could be a script or wiki page with commands.

From SonarQube:

> I also asked about what are the conditions to be part of the Update Center from SonarQube (access to updates directly from the UI), as the feature will probably interested you.
> Conditions are:
> Request For Feedback (RFF) period on the mailing list.
> At the end of the RFF, notify a SonarQube(SQ) member through the google group thread, and provide the following information:
> - short description of the version
> - SQ versions compatibility
> - Changelog URL
> - download URL
> 
> Our google group is: https://groups.google.com/forum/#!forum/sonarqube
> You can directly send an email to the group by using the following email: sonarqube@googlegroups.com
> 
> A few example of RFF thread:
> [Java 3.13](https://groups.google.com/d/topic/sonarqube/tGhp6Af8Wik/discussion)
> [GitHub Plugin 1.2](https://groups.google.com/d/topic/sonarqube/y9FQz8_PPIE/discussion)
> [Javascript 2.12](https://groups.google.com/d/topic/sonarqube/Mg7uA8f2YNg/discussion)
> [Java Properties 1.6](https://groups.google.com/d/topic/sonarqube/Qd_mKlAh1-U/discussion)

**Comment by tsjensen** [comment]
You might consider using `org.checkstyle.sonarqube` as group ID. Of course that would mean moving the whole of Checkstyle to the `checkstyle.org` domain. But Daniil already owns the domain, so it could be done. Also, package names etc. could be consolidated and become independent of the source host (SF, GitHub). Just a thought.

**Comment by romani** [comment]
For now my position is to invest no money to project till project start earning money.

We took domain just in case.

Too much need to be done with stability of project, too early to speak about cosmetic changes - good named hosting, .... . We have very tiny team.

For now we can take "com.github.checkstyle" groupId , Maven will be ok with such group, users do not care, as they will download it from Sonar plugin repository.

Sonar-checkstyle just lack of my attention ..... too much activity in main project. New contributors are welcome.

**Comment by tsjensen** [comment]
OK, as you wish. But just to be sure: It does *not* require money - you can host stuff entirely with free GitHub features and still use your own domain. I do that with [Checkstyle Addons](http://checkstyle-addons.thomasjensen.com/).

**Comment by romani** [comment]
release 3.1 - https://github.com/checkstyle/sonar-checkstyle/releases/tag/3.1

**Comment by romani** [comment]
release is sent to sonarqube repo: https://groups.google.com/forum/#!topic/sonarqube/l9sCzhjOxr8

**Comment by romani** [comment]
> https://repo1.maven.org/maven2/com/github/

no need to make it available in maven repo, as it will never be used as maven dependency.
we will store binaries in github, see "Downloads" at https://github.com/checkstyle/sonar-checkstyle/releases

**Comment by romani** [comment]
release instructions are at - https://github.com/checkstyle/sonar-checkstyle/wiki/How-to-make-release
