### ISSUE TITLE
Options for WhitespaceAround too long

### ISSUE THREAD

**Issue by marschall** [checkstyle/sonar-checkstyle#75]
Sonar version: 5.6.5
Checkstyle sonar plugin verson: 3.6-SNAPSHOT

Steps to reproduce or description of problem:

When I start SonarQube I get the following error
```
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "PARAM_TYPE VARCHAR(512) NOT NULL": "'SINGLE_SELECT_LIST,multiple=true,values=""ASSIGN,ARRAY_INIT,BAND,BAND_ASSIGN,BOR,BOR_ASSIGN,BSR,BSR_ASSIGN,BXOR,BXOR_ASSIGN,COLO... (549)"; SQL statement:
INSERT INTO rules_parameters (rule_id, name, param_type, default_value, description)
    VALUES (?, ?, ?, ?, ?) [22001-176]
```

It looks as if this is caused by the options for WhitespaceAroundCheck introduced in #67.

**Comment by rnveach** [comment]
@romani How are we fixing this? Is this just a issue with the rule file?

The mentioned fix https://github.com/checkstyle/sonar-checkstyle/commit/40849879ace9c87080c7e07b5398fb9b60f2254f#diff-7e847188273a49bacd3f0bad7feffc1aR1606, puts all the tokens in the `type` field which is what is causing the error `Value too long for column "PARAM_TYPE VARCHAR(512) NOT NULL"`.

Other checks just list said type as `STRING`. https://github.com/checkstyle/sonar-checkstyle/blob/40849879ace9c87080c7e07b5398fb9b60f2254f/checkstyle-sonar-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L82-L84

Should we stick to all tokens in type and just default to `STRING` if list becomes too long?

**Comment by romani** [comment]
If it will work, I am fine with such fix.

**Comment by marschall** [comment]
I recommendation would be to go simply with `STRING` as well.

**Comment by rnveach** [comment]
I don't have a working sonar to test and play with yet, but how big is the default value field which also can hold the same information?

**Comment by marschall** [comment]
`rules_parameters.default_value` is `VARCHAR(4000)` but `rules_parameters.param_type` is only `VARCHAR(512)`

**Comment by romani** [comment]
I tested datatype conversion to STRING - it works fine, rule works fine.
Looks like sonar do maintenance of types on DB himself.

so in 3.6: we convert type from "s{}" to "STRING" and it works fine.
