### ISSUE TITLE
validate Sonar status after merge to master

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#76]
Sonar team will not accept plugin release to their repository that have Bug or Vulnerabilities.
https://sonarqube.com/dashboard/index/com.github.checkstyle:checkstyle-sonar-plugin-parent

try to use:
https://sonarqube.com/web_api/
to fail build in master as soon some leak happened. This will help us resolve  the problem sooner after merge.

**Comment by muhlba91** [comment]
@romani shouldn't this be addressed by the sonarcloud.io integration now?

**Comment by romani** [comment]
Wrecker do sonarqube execution on master and pr
