### ISSUE TITLE
virus/malware alert for checkstyle-sonar-plugin-3.5.1.jar

### ISSUE THREAD

**Issue by FrVaBe** [checkstyle/sonar-checkstyle#79]
Sonar version: 4.5.6
Checkstyle sonar plugin verson: 5.6.5

Steps to reproduce or description of problem:
* Have Avira Professional Security installed (newest definition file version 22.02.2017)
* do a `mvn sonar:sonar` analysis on a Java project

Hi,

today my SonarQube (5.6.5) analysis via Maven failed because of a virus/malware alert.

```
Object: checkstyle-sonar-plugin-3.5.1.jar
Alert: TR/Fortnight.C
Virus Software: Avira Professional Security
```

Message (german):

> Beim Zugriff auf Daten über die URL "http://....../checkstyle-sonar-plugin-3.5.1.jar"
> wurde eine verdächtige Datei / ein verdächtiges Muster 'TR/Fortnight.C' [trojan] gefunden.
> Ausgeführte Aktion: Der Zugriff auf die Datei wurde blockiert

I hope this is a false/positive but thought it would be good for you to know.
Are you aware of this "issue"?

Maybe the file should be reported to Avira as False/Positive. I can do this if you like.

Kind regards,
  Franz

**Comment by romani** [comment]
Thanks a lot for reporting this. I do not know this tool.
Please report this to them on our behalf, if they point to problematic code we could fix it.

I am closing issue, because we can not do anything for now. Discussion could be continued

**Comment by FrVaBe** [comment]
I reported the file to Avira. Strange is that the file is not reported when it is downloaded from GitHub via the Brower nor does https://www.virustotal.com detects any virus/malware (even not for Avira).
The virus alert only happens when the file is downloaded by the sonar-maven-plugin from our local SonarQube installation. I already deinstalled and reinstalled the plugin to be sure to not have a corrupted file but that did not change anything.
I will keep you updated on any news.

**Comment by FrVaBe** [comment]
Noticed the new Release 3.6. As the virus alert for 3.5.1 still exists for me I am curious if I can update the pluging already (SonarQube 5.6.5)? The update does not appears in the SonarQube Update Center yet - but I would like to update as soon as possible. Is it OK to do it manually already?

**Comment by romani** [comment]
manual update is the same.

Upload "SonarQube Update Center" will be done in 2 weeks after RFF https://groups.google.com/forum/#!topic/sonarqube/qeOjxisnNiY, it is a process enforced by Sonar team to let smb provide feeedback on release before upload to "SonarQube Update Center".

You can try and share feedback on 3.6 on mail-list.

**Comment by FrVaBe** [comment]
I get the same alert with version 3.6. Really weird behaviour. I went back to 'sonar-checkstyle-plugin-2.4.jar'. I think I was on that version when SonarQube offers update to 3.5.1. No update notifcations to earlier 3.x version werer raised as far as I remember.
I even wonder when the `sonar-checkstyle-plugin` binary was renamend to `checkstyle-sonar-plugin`. Or are these different checkstyle plugins?

**Comment by romani** [comment]
We changed name as plugin is not under Sonar team any more. Code is the same in general. You can compare it yourself.

We did this on first 3.1 version.

All versions are at https://github.com/checkstyle/sonar-checkstyle/releases
We only recently figured out how to pass procedure to Sonar Update Center.

You have this alert probably because jar is not signed.  Can you test sign of 2.x and 3.x ?

**Comment by FrVaBe** [comment]
Thanks for the background information. What do you mean by "test sign"? Version 2.4 works well for me. Which versions of 3.x should I test and what should I do? I am glad to help.

**Comment by romani** [comment]
smth like https://docs.oracle.com/javase/tutorial/deployment/jar/verify.html

**Comment by FrVaBe** [comment]
All version from 2.3 up to 3.6 are reported as unsigned.
Even the sonar-java-plugin-4.5.0.8398.jar which I use is not signed. 
Thus I doubt that the alert is related to the missing signature.

**Comment by FrVaBe** [comment]
We finally removed the checkstyle plugin from our SonarQube installation as we do not use any checkstyle rules anyway. So this is no more issue for me.

Nevertheless a pity that I could not (help to) solve the problem.
