### ISSUE TITLE
is it possible to run the checkstyle plugin prior to the sonar-scanner run and feed the results in as input to parallelize some tasks?

### ISSUE THREAD

**Issue by juliangamble** [checkstyle/sonar-checkstyle#84]
Sonar version: 5.5
Checkstyle sonar plugin verson: 2.4

Steps to reproduce or description of problem:
Running sonar scan with checkstyle. 

The sonar-scanner takes a long time (after the tests have completed). 

We'd like to run the checkstyle run in parallel with the tests running (on another server) and then use the output of the checkstyle run as input to the sonar scanner. 

My question is: **is it possible to run the checkstyle plugin prior to the sonar-scanner run and feed the results in as input to parallelize some tasks?**

**Comment by romani** [comment]
I doubt that this is in control of plugin, it just follow sonar workflow. Sonar server call us when it required.
You need to ask this on sonar Google Group.

Non of plugins could run on remote host as far as I know.
Parallel execution is also tricky in maven build, I doubt maven plugin could do this.
