### ISSUE TITLE
Improper validation error when creating a custom rule

### ISSUE THREAD

**Issue by rnveach** [checkstyle/sonar-checkstyle#88]
I got the following red ball error when adding a custom rule for `Illegal Token Text`.
I missed filling in the property `ignoreCase` but validation error didn't make that clear.

![sonar validation](https://cloud.githubusercontent.com/assets/5427943/24024806/732cfe28-0a8c-11e7-8ba7-3b571d8f3b80.png)

Error message says `Value '' must be one of "true" or "false".` but I assume what is the property name is just turned into an empty string (`''`).
It should be the name of the property otherwise it won't make sense if a check has multiple `true`/`false` properties.

**Comment by muhlba91** [comment]
we moved to a new metadata mechanism, and properties (types, ...) are set based on this. closing this as stale, and should be fixed. please reopen if issue still persists with new up-to-date information.
