### ISSUE TITLE
UT validation for check documentation

### ISSUE THREAD

**Issue by rnveach** [checkstyle/sonar-checkstyle#89]
Taken from https://github.com/checkstyle/sonar-checkstyle/issues/28#issue-195158019 ,

https://github.com/checkstyle/sonar-checkstyle/tree/1e94e2a197deffc0b64e2320e14e0ea597a86f21/checkstyle-sonar-plugin/src/main/resources/org/sonar/l10n/checkstyle/rules/checkstyle

We need a UT to validate these files.
They should exist for each Checkstyle check, should contain something. We shouldn't have excess files.

It should be investigated where these texts are displayed in sonarqube, and how we should validate their contents against Checkstyle's own XDOC documentation.

**Comment by romani** [comment]
may be it is better to have link to our website instead of "copy-paste" from xdoc (while we do not have tool that can generate proper content) ?

**Comment by rnveach** [comment]
All files exist that should exist.
There is one excess file that can be removed: `com.puppycrawl.tools.checkstyle.checks.RegexpCheck.html`
It should be in the `regexp` package but there is already a file with that name.
