### ISSUE TITLE
why SuppressWarningsFilter and SuppressionCommentFilter are default filters ?

### ISSUE THREAD

**Issue by rnveach** [checkstyle/sonar-checkstyle#98]
When I define one rule in a sonar profile, like `Indentation`, the following configuration is created:
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
"http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<!-- Generated by Sonar -->
<module name="Checker">
  <module name="SuppressionCommentFilter"/>
  <module name="SuppressWarningsFilter"/>
  <module name="TreeWalker">
    <module name="FileContentsHolder"/>
    <module name="SuppressWarningsHolder"/>
    <module name="Indentation">
      <property name="severity" value="info"/>
      <property name="throwsIndent" value="4"/>
      <property name="arrayInitIndent" value="4"/>
      <property name="forceStrictCondition" value="false"/>
      <property name="caseIndent" value="4"/>
      <property name="basicOffset" value="4"/>
      <property name="braceAdjustment" value="0"/>
      <property name="lineWrappingIndentation" value="4"/>
    </module>
  </module>
</module>

````

The addition of the default filters `SuppressWarningsFilter` and `SuppressionCommentFilter` were unexpected and were causing issues for me.

`SuppressWarningsFilter` by default will hide any violations when `SuppressWarnings` is used with it. I had added `SuppressWarnings` annotations for other tests.
So I can't get violations in the following java file unless `SuppressWarningsFilter` is removed:

````
import java.lang.Boolean;

public class Testing {
    @SuppressWarnings("all")
    public void method() {
		test:
		;

        Boolean s = new Boolean("testing");
        Boolean t = new java.lang.Boolean("test");
        
        new Thread(
    		() -> System.out.println("hello world")
    	).start();
int a = 0;
a++;
    }

    @SuppressWarnings("   ")
    public void test() {
    }

	public @interface NonNull {
	}
	/** */
	public @interface NonNull2 {
	}
}
````

**Comment by romani** [comment]
How default value is looks like in sonar:
![image](https://cloud.githubusercontent.com/assets/812984/24724912/c39d2bba-1a01-11e7-848c-6d1afc4861af.png)

**Comment by romani** [comment]
> The addition of the default filters SuppressWarningsFilter and SuppressionCommentFilter were unexpected and were causing issues for me.

Do you propose to make default as nothing (empty string) ?

> It should also be noted since we are auto-adding FileContentsHolder and SuppressWarningsHolder

Let make separate issue on this. As it is separate issue.

**Comment by rnveach** [comment]
> Do you propose to make default as nothing (empty string) ?

I did.
Does the screenshot mean that filters are global and each profile can't define it's own filters like rules?

**Comment by romani** [comment]
No, each project can override this value, to make it specific to the project in Administation menu of certain project.
![image](https://cloud.githubusercontent.com/assets/812984/24730743/53b5e95e-1a1a-11e7-9128-4590da163746.png)
Default is value from global Sonar Administration menu.

**Comment by muhlba91** [comment]
has been moved into #99 - closing this one.
